// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemplateService.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Overt.GrpcTemplate.Service.Grpc {
  public static partial class TemplateService
  {
    static readonly string __ServiceName = "Overt.GrpcTemplate.Service.Grpc.TemplateService";

    static readonly grpc::Marshaller<global::Overt.GrpcTemplate.Service.Grpc.EmptyRequest> __Marshaller_EmptyRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Overt.GrpcTemplate.Service.Grpc.EmptyRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Overt.GrpcTemplate.Service.Grpc.EmptyResponse> __Marshaller_EmptyResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Overt.GrpcTemplate.Service.Grpc.EmptyResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Overt.GrpcTemplate.Service.Grpc.EmptyRequest, global::Overt.GrpcTemplate.Service.Grpc.EmptyResponse> __Method_Logs_Execute = new grpc::Method<global::Overt.GrpcTemplate.Service.Grpc.EmptyRequest, global::Overt.GrpcTemplate.Service.Grpc.EmptyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Logs_Execute",
        __Marshaller_EmptyRequest,
        __Marshaller_EmptyResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Overt.GrpcTemplate.Service.Grpc.TemplateServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TemplateService</summary>
    public abstract partial class TemplateServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Overt.GrpcTemplate.Service.Grpc.EmptyResponse> Logs_Execute(global::Overt.GrpcTemplate.Service.Grpc.EmptyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TemplateService</summary>
    public partial class TemplateServiceClient : grpc::ClientBase<TemplateServiceClient>
    {
      /// <summary>Creates a new client for TemplateService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TemplateServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TemplateService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TemplateServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TemplateServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TemplateServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Overt.GrpcTemplate.Service.Grpc.EmptyResponse Logs_Execute(global::Overt.GrpcTemplate.Service.Grpc.EmptyRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Logs_Execute(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Overt.GrpcTemplate.Service.Grpc.EmptyResponse Logs_Execute(global::Overt.GrpcTemplate.Service.Grpc.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Logs_Execute, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Overt.GrpcTemplate.Service.Grpc.EmptyResponse> Logs_ExecuteAsync(global::Overt.GrpcTemplate.Service.Grpc.EmptyRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Logs_ExecuteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Overt.GrpcTemplate.Service.Grpc.EmptyResponse> Logs_ExecuteAsync(global::Overt.GrpcTemplate.Service.Grpc.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Logs_Execute, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TemplateServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TemplateServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TemplateServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Logs_Execute, serviceImpl.Logs_Execute).Build();
    }

  }
}
#endregion
