// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemplateService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Overt.GrpcTemplate.Service.Grpc {

  /// <summary>Holder for reflection information generated from TemplateService.proto</summary>
  public static partial class TemplateServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for TemplateService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TemplateServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVUZW1wbGF0ZVNlcnZpY2UucHJvdG8SH1NvZGFvLkdycGNUZW1wbGF0ZS5T",
            "ZXJ2aWNlLkdycGMaDENvbW1vbi5wcm90bzKCAQoPVGVtcGxhdGVTZXJ2aWNl",
            "Em8KDExvZ3NfRXhlY3V0ZRItLlNvZGFvLkdycGNUZW1wbGF0ZS5TZXJ2aWNl",
            "LkdycGMuRW1wdHlSZXF1ZXN0Gi4uU29kYW8uR3JwY1RlbXBsYXRlLlNlcnZp",
            "Y2UuR3JwYy5FbXB0eVJlc3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Overt.GrpcTemplate.Service.Grpc.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
